spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: auth_route
          uri: lb://user-auth
          predicates:
          - Path=/api/auth/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: user_route
          uri: lb://sysuser-server
          predicates:
          - Path=/api/user/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ninja_route
          uri: lb://ninja-server
          predicates:
          - Path=/api/ninja/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}
server:
  port: 88